[package]
name = "aurum"
version = "0.1.0"
authors = ["Arjun Shukla <arjunlalshukla@gmail.com>"]
edition = "2018"

[dependencies]
aurum_macros = { path = "src/macros" }
async-trait = "*"
byteorder = "*"
crdts = "*"
crossbeam = "*"
im = { version = "*", features = ["serde"] }
itertools = "*"
lazy_static = "*"
linked-hash-map = "*"
num_enum = "*"
once_cell = "*"
rand = "*"
rand_chacha = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
tokio = { version = "*", features = ["sync", "macros", "time", "net", "rt", "rt-multi-thread"] }
tokio-test = "*"
wyhash = "*"