[package]
name = "aurum"
version = "0.1.0"
authors = ["Arjun Shukla <arjunlalshukla@gmail.com>"]
edition = "2018"

[dependencies]
crossbeam = "0.8"
indoc = "1.0"
interface-proc = { path = "interface-proc" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.1", features = ["sync"] }