tab_spaces = 2
newline_style = "Unix"
max_width = 99
use_small_heuristics = "Off"
#chain_width = 99
#fn_call_width = 80
#fn_single_line = true

#blank_lines_lower_bound = 1
# struct_lit_width = 80
# imports_granularity = "Module"
